# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

# Use a package of configuration called an orb.
jobs:

  save_world:
    <<: *defaults
    steps:
      - run:
          name: SavingDoc
          command: echo "Hello World File" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  show_world:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: SavingDoc
          command: cat ~/output.txt

  intentional_fail:
    <<: *defaults
    steps:
    - run:
        name: Intentional Fail
        command: exit 1
    - run:
        name: callout
        command: echo "failed correctly"
        when: on_fail

  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run test

  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome-workflow-1:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires: 
            - build
      - analyze:
          requires:
            - test
      